services:
  - type: web
    name: ffmpeg-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: ffmpeg-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
