services:
  - type: web
    name: ffmpeg-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: ffmpeg-storage
      mountPath: /opt/render/project/src/storage
      sizeGB: 10
